config/routes.rb
  Rails.application.routes.draw do
  resources :images do
    # get "update_package", to: "images#new_wp", on: :new
  end


  # resources :images, path_names: { new: 'new/:is_update_package' }
  # resources :umrah_customers

  devise_for :users
  resources "home"
  # root to: "welcome#index"

  namespace :admin do
    resources :umrah_customers
    resources :umrah_packages
    resources :user_roles do
      member do
        get 'admin/user_roles', action: 'get_product', as: 'user_role_product'
      end
    end
  end

  root to: "home#index"

  get 'uploads/admin/umrah_customer/:form/:id/:filename', to: 'umrah_customers#show', as: :view_pdf_file
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin/umrah_package.rb
class Admin::UmrahPackage < ApplicationRecord
  belongs_to :image, optional: true, dependent: :destroy
  has_one :umrah_customer

  validate :price_format

  attributes_to_validate = [:title, :hotel_mekah, :hotel_madinah]
  attributes_to_validate.each do |attr|
    validates attr, presence: true
  end

  PRICE_REGEXP = /\A\d+(?:\.\d{0,2})?\z/.freeze

  accepts_nested_attributes_for :image

  def package_full_name
    [self.title,self.rooms_per_pax,"pax/room"].join(' ')
  end

  def is_poster_available
    self.image.picture.url || nil
  end

  private
  def price_format

    package_price = read_attribute_before_type_cast('price')
    price_with_no_comma = package_price.gsub(',','')

    unless price_with_no_comma =~ PRICE_REGEXP
      errors.add('price', 'must match the correct format e.g 6900.00')
    end
  end

end

app/controllers/admin/umrah_packages_controller.rb
class Admin::UmrahPackagesController < ApplicationController
  before_action :get_umrah_package_detail, only: %i[ show edit update destroy]
  layout 'admin'

  include UmrahPackageConcern

  def index
    @umrah_packages = Admin::UmrahPackage.all
  end

  def new
    @umrah_package = Admin::UmrahPackage.new
    @image_new = Image.new
  end

  def create
    @umrah_package = Admin::UmrahPackage.create(umrah_package_params)

    respond_to do |format|
      if @umrah_package.save
        format.html { redirect_to admin_umrah_packages_path, notice: "Umrah customer was successfully created." }
        format.json { render :show, status: :created, location: @umrah_package }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @umrah_package.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @image = @umrah_package.is_poster_available
  end

  def edit
    @image = @umrah_package.is_poster_available
  end

  def update
    respond_to do |format|
      if @umrah_package.update(umrah_package_params)
        format.html { redirect_to admin_umrah_packages_path, notice: "Umrah customer was successfully updated." }
        format.json { render :show, status: :ok, location: @umrah_customer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @umrah_package.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @umrah_package.destroy
    redirect_to admin_umrah_packages_path
  end

  private

  def get_umrah_package_detail
    @umrah_package = Admin::UmrahPackage.find(params[:id])
  end

  def umrah_package_params
    params
      .require(:admin_umrah_package).
      permit(
        :title,
              :package_type,
              :price,
              :hotel_mekah,
              :hotel_madinah,
              :image_id,
              :rooms_per_pax,
              image_attributes: [:name, :picture]
            )
  end

  def get_package_images
    @image = Image.all
  end

end

app/controllers/concerns/umrah_package_helper.rb
module UmrahPackageHelper

  def get_full_package_name(package)
    "#{package.title}  #{package.rooms_per_pax} pax/rooms"
  end

end

app/helpers/umrah_packages_helper.rb
module UmrahPackagesHelper
  include CostCalculatorConcern

  def calculate_package_price(price,currency)
    render_in_money_terms(price,currency)
  end
end

app/views/umrah_packages/common/_package_form.html.erb
<div class="container form-group col-md-8">
  <% @image ||= nil %>
  <%= form_with(model: @umrah_package, id: "umrah-package-form") do |form| %>

    <%= form.label :title, "Title" %>
    <%= form.text_field :title, placeholder: "e.g Umrah Safwa", class: "form-control customer-form-wrapper", disabled: disabled, id: "input" %>

    <div class="form-group select-form-margin-top">
      <%= form.label :package_type, "Umrah Type" %>
      <%= form.select :package_type, ["Umrah Standard", "Umrah Ramadhan", "Umrah Family"], { include_blank: false }, { class: "form-control customer-form-wrapper", disabled: disabled } %>
    </div>

    <div class="form-group select-form-margin-top">
      <%= form.label :rooms_per_pax, "Jemaah Per Bilik" %>
      <%= form.select :rooms_per_pax, [2, 3, 4, 5], { include_blank: false }, { class: "form-control customer-form-wrapper", disabled: disabled, id: "pax-per-room" } %>
    </div>

    <div class="form-group">
      <%= form.label :price, "Price" %>
      <br>
      <div class="row col-md-12">
        <label class="col-form-label" style="margin-top:0.5rem">RM</label>
        <div class="col-sm-11">
          <%= form.text_field :price, class: "form-control customer-form-wrapper", disabled: disabled %>
        </div>
      </div>
    </div>
    <br>
    <div class="form-group select-form-margin-top">
      <%= form.label :hotel %>
      <%= form.text_field :hotel, placeholder: "e.g Hotel Safwa", class: "form-control customer-form-wrapper", disabled: disabled %>
    </div>

    <%= form.hidden_field :package_full_name, id: 'package_full_name' %>

    <dl class="form-group">
      <dd>
        <p3>Package Poster</p3>
      </dd>
      <% if @image.present? %>
        <dd><%= image_tag(@image.picture.url, size: '150x150', class: "img-thumbnail", disabled: disabled) unless @image.picture.nil? %></dd>
        <%= link_to "Change poster", edit_image_path(@image.id, is_from_package: true, package_id: @umrah_package.id), class: "btn btn-primary text-white select-form-margin-top", style: "font-size:12px" if disabled.blank? %>
      <% elsif @enable_poster_upload %>
        <div class="form-group">
          <%= link_to "Change poster", new_image_path(is_update_poster_from_package: true, package_id: @umrah_package.id), class: "btn btn-primary text-white select-form-margin-top", style: "font-size:12px" if disabled.blank? %>
        </div>
      <% end %>
    </dl>

    <% if disabled %>
      <%= link_to "Edit Package", edit_umrah_package_path(@umrah_package.id), class: "btn btn-primary text-white select-form-margin-top", style: "font-size:12px", id: "update-package" %>
    <% else %>
      <% if @is_new_package %>
        <%= form.submit "Register New Packages", class: "btn btn-primary text-white select-form-margin-top", style: "font-size:12px", id: "update-package" %>
      <% else %>
        <%= form.submit "Update Package", { class: "btn btn-primary text-white select-form-margin-top", style: "font-size:12px", id: "update-package" } %>
      <% end %>
    <% end %>
    </div>
  <% end %>