config/routes.rb
  Rails.application.routes.draw do
  resources :images do
    # get "update_package", to: "images#new_wp", on: :new
  end


  # resources :images, path_names: { new: 'new/:is_update_package' }
  # resources :umrah_customers

  devise_for :users
  resources "home"
  # root to: "welcome#index"

  namespace :admin do
    resources :umrah_customers
    resources :umrah_packages
    resources :user_roles do
      member do
        get 'admin/user_roles', action: 'get_product', as: 'user_role_product'
      end
    end
  end

  root to: "home#index"

  get 'uploads/admin/umrah_customer/:form/:id/:filename', to: 'umrah_customers#show', as: :view_pdf_file
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin/umrah_customer.rb
class Admin::UmrahCustomer < ApplicationRecord
  attribute :total_participants, :integer, default: 1
  enum is_full_payment_made: { no_payment:0 , partial_payment: 1, full_payment: 2, extra_payment:3 }
  enum umrah_status: { Pending:0, Performing:1, Completed:2}

  # before_save :update_umrah_status

  attributes_to_validate = [
    :customer_name,
    :identification_card,
    :home_address,
    :mobile_tel,
    :citizenship,
  ]

  attributes_to_validate.each do |attr|
    validates attr, presence: true
  end

  validate :price_format
  PRICE_REGEXP = /\A\d+(?:\.\d{0,2})?\z/.freeze

  validates :identification_card, numericality: true

  belongs_to :flight_inbound_detail
  belongs_to :flight_outbound_detail
  belongs_to :umrah_package, class_name: 'Admin::UmrahPackage'

  mount_uploader :quotation_form, AttachmentUploader
  mount_uploader :registration_form, AttachmentUploader
  mount_uploader :deposit_payment, AttachmentUploader
  mount_uploader :final_payment, AttachmentUploader

  def update_umrah_status(status)
      self.umrah_status = status
  end

  def payment_status
    if self.total_paid.present?
      total_paid = self.total_paid.gsub(",", "")
      is_full_payment_made = total_paid.to_i - self.umrah_package.price.to_i
      byebug
      if total_paid.to_i == 0
        "No payment"
      elsif is_full_payment_made == 0
        "Full payment made"
      elsif is_full_payment_made < 0
        "Partial payment made"
      elsif is_full_payment_made > 0
        "Extra payment made"
      end
    end
  end

  private

  def price_format
    total_paid = read_attribute_before_type_cast('total_paid')
    total_paid_no_comma = total_paid.gsub(',', '')

    unless total_paid_no_comma =~ PRICE_REGEXP
      errors.add('total_paid', 'must match the correct format e.g 6900.00')
    end
  end

end

app/models/umrah_customer.rb
class UmrahCustomer < ApplicationRecord
  attribute :total_participants,  :integer, default: 1

  belongs_to :flight_inbound_detail
  belongs_to :flight_outbound_detail
  belongs_to :umrah_package



  mount_uploader :quotation_form, AttachmentUploader

  mount_uploader :registration_form, AttachmentUploader

  mount_uploader :deposit_payment, AttachmentUploader

  mount_uploader :final_payment, AttachmentUploader

end

app/controllers/admin/umrah_customers_controller.rb
class Admin::UmrahCustomersController < ApplicationController
  before_action :set_umrah_customer, only: %i[ show edit update destroy ]
  layout 'admin'

  include CostCalculatorConcern

  # GET /umrah_customers or /umrah_customers.json
  def index
    @umrah_customers = Admin::UmrahCustomer.all
    @is_umrah_package_available = !Admin::UmrahPackage.all.blank?
  end

  # GET /umrah_customers/1 or /umrah_customers/1.json
  def show
    update_payment_status
    @umrah_package_price = calculate_customers_total_cost(@umrah_customer)
    @customer_total_paid = calculate_total_paid(@umrah_customer)
    respond_to do |format|
      format.html { render :show, locals: { umrah_customer_params: false } }
    end
  end

  # GET /umrah_customers/new
  def new
    @umrah_customer = Admin::UmrahCustomer.new
    @new_customer = @umrah_customer
  end

  # GET /umrah_customers/1/edit
  def edit
    @umrah_customer ||= Admin::UmrahCustomer.new
    @umrah_package_price = calculate_customers_total_cost(@umrah_customer)
    @customer_total_paid = calculate_total_paid(@umrah_customer)
  end

  # POST /umrah_customers or /umrah_customers.json
  def create
    @umrah_customer = Admin::UmrahCustomer.new(umrah_customer_params)
    respond_to do |format|
      if @umrah_customer.save
        format.html { redirect_to admin_umrah_customer_path(@umrah_customer.id), notice: "Umrah customer was successfully created." }
        format.json { render :show, status: :created, location: @umrah_customer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @umrah_customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /umrah_customers/1 or /umrah_customers/1.json
  def update
    @umrah_customer.update_umrah_status(params[:admin_umrah_customer][:umrah_status_attr])
    respond_to do |format|
      if @umrah_customer.update(umrah_customer_params)
        format.html { redirect_to admin_umrah_customer_path(@umrah_customer.id), notice: "Umrah customer was successfully updated." }
        format.json { render :show, status: :ok, location: @umrah_customer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @umrah_customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /umrah_customers/1 or /umrah_customers/1.json
  def destroy
    @umrah_customer.destroy

    respond_to do |format|
      format.html { redirect_to admin_umrah_customers_url, notice: "Umrah customer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def umrah_customer_params
    params
      .require(:admin_umrah_customer)
      .permit(:customer_name,
              :house_tel,
              :home_address,
              :total_participants,
              :date_registered,
              :total_paid,
              :total_cost,
              :flight_inbound_detail_id,
              :flight_outbound_detail_id,
              :quotation_form,
              :registration_form,
              :deposit_payment,
              :final_payment,
              :umrah_package_id,
              :customer_mahram,
              :mobile_tel,
              :customer_waris_name,
              :waris_address,
              :waris_tel,
              :identification_card,
              :gender,
              :citizenship,
              :is_full_payment_made,
              :umrah_status
      )
  end

  def set_umrah_customer
    @umrah_customer = Admin::UmrahCustomer.find(params[:id])
  end

  def update_payment_status
    total_paid_in_money_format = render_in_money_terms(@umrah_customer.total_paid, "")
    total_paid = total_paid_in_money_format.gsub(",", "")
    is_full_payment_made = total_paid.to_i - @umrah_customer.umrah_package.price.to_i

    if total_paid.to_i == 0
      @umrah_customer.no_payment!
    elsif is_full_payment_made == 0
      @umrah_customer.full_payment!
    elsif is_full_payment_made < 0
      @umrah_customer.partial_payment!
    else
      @umrah_customer.extra_payment!
    end

    @umrah_customer.save
  end

end

app/controllers/umrah_customers_controller.rb
class UmrahCustomersController < ApplicationController
  before_action :set_umrah_customer, only: %i[ show edit update destroy ]
  before_action :get_flight_details, only: %i[ show new edit update destroy ]
  before_action :get_customer_payment, only: %i[ edit show update destory ]
  before_action :get_umrah_package_detail, only: %i[ new edit show update destory ]

  include UmrahCustomersHelper

  # GET /umrah_customers or /umrah_customers.json
  def index
    @umrah_customers = UmrahCustomer.all
  end

  # GET /umrah_customers/1 or /umrah_customers/1.json
  def show
    @umrah_package_price =  calculate_customers_total_cost(@umrah_customer)
    respond_to do |format|
      format.html { render :show, locals: { umrah_customer_params: false } }
    end
  end

  # GET /umrah_customers/new
  def new
    @umrah_customer = UmrahCustomer.new
    @new_customer = @umrah_customer
  end

  # GET /umrah_customers/1/edit
  def edit
    @umrah_package_price = calculate_customers_total_cost(@umrah_customer)
  end

  # POST /umrah_customers or /umrah_customers.json
  def create
    @umrah_customer = UmrahCustomer.new(umrah_customer_params)

    respond_to do |format|
      if @umrah_customer.save
        format.html { redirect_to umrah_customers_path, notice: "Umrah customer was successfully created." }
        format.json { render :show, status: :created, location: @umrah_customer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @umrah_customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /umrah_customers/1 or /umrah_customers/1.json
  def update
    respond_to do |format|
      if @umrah_customer.update(umrah_customer_params)
        format.html { redirect_to umrah_customer_path, notice: "Umrah customer was successfully updated." }
        format.json { render :show, status: :ok, location: @umrah_customer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @umrah_customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /umrah_customers/1 or /umrah_customers/1.json
  def destroy
    @umrah_customer.destroy

    respond_to do |format|
      format.html { redirect_to umrah_customers_url, notice: "Umrah customer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def get_flight_details
    @flight_inbound_detail = FlightInboundDetail.all
    @flight_outbound_detail = FlightOutboundDetail.all
  end

  def get_umrah_package_detail
    @umrah_package = UmrahPackage.all
  end

  # Only allow a list of trusted parameters through.
  def umrah_customer_params
    params.require(:umrah_customer).permit(:customer_name, :house_tel, :home_address, :total_participants, :date_registered, :total_paid, :total_cost, :flight_inbound_detail_id, :flight_outbound_detail_id, :quotation_form, :registration_form, :deposit_payment, :final_payment, :umrah_package_id, :customer_mahram, :mobile_tel, :customer_waris_name, :waris_address, :waris_tel, :identification_card, :gender, :citizenship)
  end

  def get_customer_payment
    @customer_total_paid = get_total_paid
  end

end

app/helpers/admin/umrah_customers_helper.rb
module Admin
  module UmrahCustomersHelper

    def calculate_customers_total_cost(umrah_customer)
      total_package_cost = umrah_customer.umrah_package.price * umrah_customer.total_participants || 0
      ActionController::Base.helpers.number_to_currency(total_package_cost, :unit => "RM")
    end

    def get_total_paid
      @umrah_customer.total_paid.to_s
    end

    def render_status(status)
      if status.kind_of?(Array)
        status.map { |params| params.split("_").map { |status| status.capitalize
        }.join(" ")}
      else
        status.split("_").map { |status| status.capitalize
        }.join(" ")
      end
    end

  end
end

app/views/admin/umrah_customers/form_detail/_customer_data.html.erb
<div style="width:100%;border-style:outset">
  <div class="form-row col-md-10">
    <div class="form-group col-10 customer-form-text-style">
      <div class="row col-10"><%= form.label :customer_name, "Nama Penuh" %><span>*</span></div>
      <%= form.text_field :customer_name, class: "form-control customer-form-wrapper", value: @umrah_customer.customer_name, readonly: is_display_only %>
    </div>

    <div class="form-group col-10 customer-form-text-style">
      <div class="row col-10"><%= form.label :identification_card, "Numbor I/C" %><span>*</span><span>(e.g 871013681234)</span></div>
      <%= form.text_field :identification_card, class: "form-control customer-form-wrapper", value: @umrah_customer.identification_card, readonly: is_display_only %>
    </div>

    <div class="form-group col-10 customer-form-text-style">
      <%= form.label :gender, "Jantina" %>
      <%= form.select :gender, %w[Lelaki Perempuan], { include_blank: false }, { class: "form-control customer-form-wrapper", readonly: is_display_only } %>
    </div>

    <div class="form-group col-10 customer-form-text-style">
      <div class="row col-10"><%= form.label :citizenship, "Warganegara" %><span>*</span></div>
      <%= form.text_field :citizenship, class: "form-control customer-form-wrapper", value: @umrah_customer.citizenship, readonly: is_display_only %>
    </div>

    <div class="form-group col-10 customer-form-text-style">
      <%= form.label :customer_mahram, "Nama Mahram" %>
      <%= form.text_field :customer_mahram, class: "form-control customer-form-wrapper", value: @umrah_customer.customer_mahram, readonly: is_display_only %>
    </div>

    <div class="form-group col-10 customer-form-text-style">
      <div class="row col-10"><%= form.label :home_address, "Alamat Rumah" %><span>*</span></div>
      <%= form.text_field :home_address, class: "form-control customer-form-wrapper", value: @umrah_customer.home_address, readonly: is_display_only %>
    </div>

    <div class="form-row col-md-10">
      <div class="form-group col-md-5 customer-form-text-style">
        <%= form.label :house_tel, "Telefon Rumah" %>
        <%= form.text_field :house_tel, class: "form-control customer-form-wrapper", value: @umrah_customer.house_tel, readonly: is_display_only, id: 'customer_phone_number' %>
        <p id="update_phone_error_message"></p>
      </div>

      <div class="form-group col-md-5 customer-form-text-style">
        <div class="row col-10"><%= form.label :mobile_tel, "Telefon Bimbit" %><span>*</span></div>
        <%= form.text_field :mobile_tel, class: "form-control customer-form-wrapper", value: @umrah_customer.mobile_tel, readonly: is_display_only, id: 'customer_phone_number' %>
        <p id="update_phone_error_message"></p>
      </div>

    </div>
  </div>


</div>

app/views/admin/umrah_customers/form_detail/_customer_package.html.erb
<div style="width:100%;border-style:outset">
  <div class="form-row col-md-12">
    <div class="form-group col-md-7 customer-form-text-style">
      <%= form.label :umrah_package, "Jenis Pakej" %>
      <%= form.collection_select :umrah_package, Admin::UmrahPackage.all, :id, :package_full_name, { include_blank: false }, { class: "form-control customer-form-wrapper", readonly: is_display_only } %>
    </div>

    <div class="form-group col-md-3 customer-form-text-style">
      <%= form.label :date_registered, "Date Registered", style: 'font-size:12px' %>
      <%= form.date_field :date_registered, class: "form-control customer-form-wrapper", value: @umrah_customer.date_registered, readonly: is_display_only %>
    </div>

    <div class="form-group col-md-2 customer-form-text-style">
      <%= form.label :total_participants, "Total Participants", style: 'font-size:12px' %>
      <%= form.text_field :total_participants, class: "form-control customer-form-wrapper", value: @umrah_customer.total_participants.to_s, readonly: is_display_only %>
    </div>

    <div class="form-group col-2 customer-form-text-style">
      <%= form.label :flight_inbound_detail_id, "Departure Date", style: 'font-size:12px' %>
      <%= form.collection_select :flight_inbound_detail_id, FlightInboundDetail.all, :id, :flight_departure_date_from_saudi, { include_blank: false }, { class: "form-control customer-form-wrapper", readonly: is_display_only } %>
    </div>

    <div class="form-group col-2 customer-form-text-style">
      <%= form.label :flight_outbound_detail_id, "Return Date", style: 'font-size:12px' %>
      <%= form.collection_select :flight_outbound_detail_id, FlightOutboundDetail.all, :id, :flight_departure_date_from_kl, { include_blank: false }, { class: "form-control customer-form-wrapper", readonly: is_display_only } %>
    </div>

    <div class="form-group col-md-2 customer-form-text-style">
      <%= form.label :total_paid, "Total Paid (RM)", style: 'font-size:12px' %>
      <%= form.text_field :total_paid, class: "form-control customer-form-wrapper", value: calculate_total_paid(@umrah_customer), readonly: is_display_only %>
    </div>

    <div class="form-group col-md-2 customer-form-text-style">
      <%= form.label :total_cost, "Total Cost", style: 'font-size:12px' %>
      <span class="form-control customer-form-wrapper" style="background-color:#C5C6D0"><%= calculate_customers_total_cost(@umrah_customer) %></span>
    </div>

    <div class="form-group col-md-2 customer-form-text-style">
      <%= render partial: 'admin/umrah_customers/common/payment_status' , locals: { form: form ,  payment_status: @umrah_customer.is_full_payment_made } %>
    </div>
  </div>
</div>

app/views/admin/umrah_customers/form_detail/_customer_waris.html.erb
<div style="width:100%;border-style:outset">

  <div class="form-group col-10 customer-form-text-style">
    <%= form.label :customer_waris_name, "Nama Waris" %>
    <%= form.text_field :customer_waris_name, class: "form-control customer-form-wrapper", value: @umrah_customer.customer_waris_name, readonly: is_display_only %>
  </div>

  <div class="form-group col-10 customer-form-text-style">
    <%= form.label :waris_address, "Alamat Waris" %>
    <%= form.text_field :waris_address, class: "form-control customer-form-wrapper", value: @umrah_customer.waris_address, readonly: is_display_only %>
  </div>

  <div class="form-group col-2 customer-form-text-style">
    <%= form.label :waris_tel, "Telefon Waris" %>
    <%= form.text_field :waris_tel, class: "form-control customer-form-wrapper", value: @umrah_customer.waris_tel, readonly: is_display_only, id: 'customer_phone_number' %>
    <p id="update_phone_error_message"></p>
  </div>
</div>

app/views/admin/umrah_customers/form_detail/_documentation_form.html.erb
<div style="width:100%;border-style:outset">
  <div class="form-group row offset-md-1 customer-form-text-style">
    <%= form.label :quotation_form, :class => 'control-label col-lg-2' %>
    <% if @umrah_customer.quotation_form.present? %>
      <% quotation_form = @umrah_customer.quotation_form.identifier %>
      <%= link_to quotation_form, view_pdf_file_path(id: @umrah_customer.id, filename: quotation_form, form: 'quotation_form'), target: :_blank, title: "Click to open", class: "col-lg-10" %>
    <% else %>
      <% if is_display_only %>
        <h3 class="col-lg-10">No file attached</h3>
      <% end %>
    <% end %>

    <% if !is_display_only %>
      <div class=" offset-md-2 col-lg-8 customer-form-text-style">
        <%= form.file_field :quotation_form, accept: 'image/jpeg,image/gif,image/png,application/pdf', :class => 'form-control' %>
      </div>
      <%= form.error_span(:quotation_form) %>
    <% end %>
  </div>

  <div class="form-group row offset-md-1 customer-form-text-style">
    <%= form.label :registration_form, :class => 'control-label col-lg-2' %>
    <% if @umrah_customer.registration_form.present? %>
      <% registration_form = @umrah_customer.registration_form.identifier %>
      <%= link_to registration_form, view_pdf_file_path(id: @umrah_customer.id, filename: registration_form, form: 'registration_form'), target: :_blank, title: "Click to open", class: "col-lg-10" %>
    <% else %>
      <% if is_display_only %>
        <h3 class="col-lg-10">No file attached</h3>
      <% end %>
    <% end %>

    <% if !is_display_only %>
      <div class=" offset-md-2 col-lg-8 customer-form-text-style">
        <%= form.file_field :registration_form, accept: 'image/jpeg,image/gif,image/png,application/pdf', :class => 'form-control' %>
      </div>
      <%= form.error_span(:registration_form) %>
    <% end %>
  </div>

  <div class="form-group row offset-md-1 customer-form-text-style">
    <%= form.label :deposit_payment, :class => 'control-label col-lg-2' %>
    <% if @umrah_customer.deposit_payment.present? %>
      <% deposit_payment = @umrah_customer.deposit_payment.identifier %>
      <%= link_to deposit_payment, view_pdf_file_path(id: @umrah_customer.id, filename: deposit_payment, form: 'deposit_payment'), target: :_blank, title: "Click to open", class: "col-lg-10" %>
    <% else %>
      <% if is_display_only %>
        <h3 class="col-lg-10">No file attached</h3>
      <% end %>
    <% end %>

    <% if !is_display_only %>
      <div class=" offset-md-2 col-lg-8 customer-form-text-style">
        <%= form.file_field :deposit_payment, accept: 'image/jpeg,image/gif,image/png,application/pdf', :class => 'form-control' %>
      </div>
      <%= form.error_span(:deposit_payment) %>
    <% end %>
  </div>

  <div class="form-group row offset-md-1 customer-form-text-style">
    <%= form.label :final_payment, :class => 'control-label col-lg-2' %>
    <% if @umrah_customer.final_payment.present? %>
      <% final_payment = @umrah_customer.final_payment.identifier %>
      <%= link_to final_payment, view_pdf_file_path(id: @umrah_customer.id, filename: final_payment, form: 'final_payment'), target: :_blank, title: "Click to open", class: "col-lg-10" %>
    <% else %>
      <% if is_display_only %>
        <h3 class="col-lg-10">No file attached</h3>
      <% end %>
    <% end %>

    <% if !is_display_only %>
      <div class=" offset-md-2 col-lg-8 customer-form-text-style">
        <%= form.file_field :final_payment, accept: 'image/jpeg,image/gif,image/png,application/pdf', :class => 'form-control' %>
      </div>
      <%= form.error_span(:final_payment) %>
    <% end %>
  </div>
</div>

app/views/admin/umrah_customers/form_detail/_umrah_status.html.erb
<div style="width:100%;border-style:outset">
  <div class="form-group col-md-7 customer-form-text-style">
    <div class="form-row col-md-10">
      <%= form.label :umrah_status_attr, "Umrah Statuss" %>
      <%= form.select :umrah_status_attr, Admin::UmrahCustomer.umrah_statuses.keys, { include_blank: false, selected: @umrah_customer.umrah_status }, { class: "form-control customer-form-wrapper", readonly: is_display_only } %>
    </div>
  </div>
</div>