config/routes.rb
  Rails.application.routes.draw do
  resources :images do
    # get "update_package", to: "images#new_wp", on: :new
  end


  # resources :images, path_names: { new: 'new/:is_update_package' }
  # resources :umrah_customers

  devise_for :users
  resources "home"
  # root to: "welcome#index"

  namespace :admin do
    resources :umrah_customers
    resources :umrah_packages
    resources :user_roles do
      member do
        get 'admin/user_roles', action: 'get_product', as: 'user_role_product'
      end
    end
  end

  root to: "home#index"

  get 'uploads/admin/umrah_customer/:form/:id/:filename', to: 'umrah_customers#show', as: :view_pdf_file
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin/umrah_package.rb
class Admin::UmrahPackage < ApplicationRecord
  belongs_to :image, optional: true, dependent: :destroy
  has_one :umrah_customer

  validate :price_format

  attributes_to_validate = [:title, :hotel_mekah, :hotel_madinah]
  attributes_to_validate.each do |attr|
    validates attr, presence: true
  end

  PRICE_REGEXP = /\A\d+(?:\.\d{0,2})?\z/.freeze

  accepts_nested_attributes_for :image

  def package_full_name
    [self.title,self.rooms_per_pax,"pax/room"].join(' ')
  end

  def is_poster_available
    self.image.picture.url || nil
  end

  private
  def price_format

    package_price = read_attribute_before_type_cast('price')
    price_with_no_comma = package_price.gsub(',','')

    unless price_with_no_comma =~ PRICE_REGEXP
      errors.add('price', 'must match the correct format e.g 6900.00')
    end
  end

end

app/controllers/admin/umrah_packages_controller.rb
class Admin::UmrahPackagesController < ApplicationController
  before_action :get_umrah_package_detail, only: %i[ show edit update destroy]
  layout 'admin'

  include UmrahPackageConcern

  def index
    @umrah_packages = Admin::UmrahPackage.all
  end

  def new
    @umrah_package = Admin::UmrahPackage.new
    @image_new = Image.new
  end

  def create
    @umrah_package = Admin::UmrahPackage.create(umrah_package_params)

    respond_to do |format|
      if @umrah_package.save
        format.html { redirect_to admin_umrah_packages_path, notice: "Umrah customer was successfully created." }
        format.json { render :show, status: :created, location: @umrah_package }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @umrah_package.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @image = @umrah_package.is_poster_available
  end

  def edit
    @image = @umrah_package.is_poster_available
  end

  def update
    respond_to do |format|
      if @umrah_package.update(umrah_package_params)
        format.html { redirect_to admin_umrah_packages_path, notice: "Umrah customer was successfully updated." }
        format.json { render :show, status: :ok, location: @umrah_customer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @umrah_package.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @umrah_package.destroy
    redirect_to admin_umrah_packages_path
  end

  private

  def get_umrah_package_detail
    @umrah_package = Admin::UmrahPackage.find(params[:id])
  end

  def umrah_package_params
    params
      .require(:admin_umrah_package).
      permit(
        :title,
              :package_type,
              :price,
              :hotel_mekah,
              :hotel_madinah,
              :image_id,
              :rooms_per_pax,
              image_attributes: [:name, :picture]
            )
  end

  def get_package_images
    @image = Image.all
  end

end

app/controllers/concerns/umrah_package_helper.rb
module UmrahPackageHelper

  def get_full_package_name(package)
    "#{package.title}  #{package.rooms_per_pax} pax/rooms"
  end

end

app/helpers/umrah_packages_helper.rb
module UmrahPackagesHelper
  include CostCalculatorConcern

  def calculate_package_price(price,currency)
    render_in_money_terms(price,currency)
  end
end

app/views/admin/umrah_packages/_form.html.erb
<div class="col-md-2">
  <%= render 'layouts/sidebar' %>
</div>
<%= form_with(model: umrah_package) do |form| %>
  <% if umrah_package.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(umrah_package.errors.count, "error") %> prohibited this umrah_package from being saved:</h2>

      <ul>
        <% umrah_package.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/umrah_packages/_umrah_package.html.erb
<tbody>
<tr>
  <th scope="row" class="counterCell"></th>
  <td><%= umrah_package.title %></td>
  <td><%= umrah_package.package_type %></td>
  <td><%= calculate_package_price(umrah_package.price, "RM") %></td>
  <td><%= umrah_package.hotel_mekah %></td>
  <td><%= umrah_package.hotel_madinah %></td>
  <td><%= umrah_package.rooms_per_pax %></td>
  <td>
    <%= link_to "View Detail", admin_umrah_package_path(umrah_package.id, is_poster_for_package: true), method: :get, class: "btn btn-primary btn-sm primary_button_text text-white", style: "font-size:12px" %>
  </td>
  <td>
    <% if umrah_package.umrah_customer.blank? %>
      <%= link_to "Delete Package", admin_umrah_package_path(umrah_package.id), method: :delete, class: "btn btn-danger btn-sm primary_button_text text-white", style: "font-size:12px" %>
    <% end %>
  </td>
</tr>
</tbody>

app/views/admin/umrah_packages/edit.html.erb
<div class="row">
  <div class="col-md-8">
    <h1>Editing Umrah Package</h1>
    <%= link_to 'Show', @umrah_package %> |
    <%= link_to 'Back', admin_umrah_packages_path %>
    <%= render partial: "admin/umrah_packages/common/package_form", locals: { disabled: false } %>
  </div>
</div>

app/views/admin/umrah_packages/index.html.erb
<div class="row">
  <div class="col-md-8">
    <p id="notice"><%= notice %></p>
    <h1 class="admin-title">Umrah Packages</h1>
    </table>
    <div class="container">
      <% unless @umrah_packages.nil? %>
        <table class="table col-sm-10 align-self-center ">
          <thead class="thead-dark ">
          <tr>
            <th scope="col">No</th>
            <th scope="col">Package Name</th>
            <th scope="col">Package Type</th>
            <th scope="col">Price</th>
            <th scope="col">Hotel Mekah</th>
            <th scope="col">Hotel Madinah</th>
            <th scope="col">Pax Per Room</th>
            <th scope="col"></th>
            <th scope="col"></th>
          </tr>
          </thead>
          <tbody>
<!--          render collection-->
          <%= render @umrah_packages %>
          </tbody>
        </table>
      <% else %>
        <%= link_to "Create New Package", new_admin_umrah_package_path, method: :get, class: "btn btn-primary btn-sm primary_button_text text-white", style: "font-size:12px" %>
      <% end %>
    </div>
    <br>
    <%= link_to 'New Umrah Package', new_admin_umrah_package_path, class: "btn btn-primary btn-sm primary_button_text text-white", style: "font-size:12px" %>
  </div>
</div>

app/views/admin/umrah_packages/new.html.erb
<div class="row">
  <div class="col-md-8">
    <p id="notice"><%= notice %></p>
    <h1 class="admin-title">Umrah Packages</h1>
    <br>
    <h1> Create New Package</h1>
    <%= render partial: "admin/umrah_packages/common/package_form", locals: { disabled: false } %>
  </div>
</div>

app/views/admin/umrah_packages/show.html.erb
<div class="row">
  <div class="col-md-8">
    <p id="notice"><%= notice %></p>
    <h1 class="admin-title">View Umrah Package</h1>
    <%= render partial: "admin/umrah_packages/common/package_form", locals: { disabled: true } %>
  </div>
</div>