config/routes.rb
  Rails.application.routes.draw do
  resources :images do
    # get "update_package", to: "images#new_wp", on: :new
  end


  # resources :images, path_names: { new: 'new/:is_update_package' }
  # resources :umrah_customers

  devise_for :users
  resources "home"
  # root to: "welcome#index"

  namespace :admin do
    resources :umrah_customers
    resources :umrah_packages
    resources :user_roles do
      member do
        get 'admin/user_roles', action: 'get_product', as: 'user_role_product'
      end
    end
  end

  root to: "home#index"

  get 'uploads/admin/umrah_customer/:form/:id/:filename', to: 'umrah_customers#show', as: :view_pdf_file
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin/umrah_customer.rb
class Admin::UmrahCustomer < ApplicationRecord
  attribute :total_participants, :integer, default: 1
  enum is_full_payment_made: { no_payment:0 , partial_payment: 1, full_payment: 2, extra_payment:3 }
  enum umrah_status: { Pending:0, Performing:1, Completed:2}

  # before_save :update_umrah_status

  attributes_to_validate = [
    :customer_name,
    :identification_card,
    :home_address,
    :mobile_tel,
    :citizenship,
  ]

  attributes_to_validate.each do |attr|
    validates attr, presence: true
  end

  validate :price_format
  PRICE_REGEXP = /\A\d+(?:\.\d{0,2})?\z/.freeze

  validates :identification_card, numericality: true

  belongs_to :flight_inbound_detail
  belongs_to :flight_outbound_detail
  belongs_to :umrah_package, class_name: 'Admin::UmrahPackage'

  mount_uploader :quotation_form, AttachmentUploader
  mount_uploader :registration_form, AttachmentUploader
  mount_uploader :deposit_payment, AttachmentUploader
  mount_uploader :final_payment, AttachmentUploader

  def update_umrah_status(status)
      self.umrah_status = status
  end

  def payment_status
    if self.total_paid.present?
      total_paid = self.total_paid.gsub(",", "")
      is_full_payment_made = total_paid.to_i - self.umrah_package.price.to_i
      byebug
      if total_paid.to_i == 0
        "No payment"
      elsif is_full_payment_made == 0
        "Full payment made"
      elsif is_full_payment_made < 0
        "Partial payment made"
      elsif is_full_payment_made > 0
        "Extra payment made"
      end
    end
  end

  private

  def price_format
    total_paid = read_attribute_before_type_cast('total_paid')
    total_paid_no_comma = total_paid.gsub(',', '')

    unless total_paid_no_comma =~ PRICE_REGEXP
      errors.add('total_paid', 'must match the correct format e.g 6900.00')
    end
  end

end

app/models/umrah_customer.rb
class UmrahCustomer < ApplicationRecord
  attribute :total_participants,  :integer, default: 1

  belongs_to :flight_inbound_detail
  belongs_to :flight_outbound_detail
  belongs_to :umrah_package



  mount_uploader :quotation_form, AttachmentUploader

  mount_uploader :registration_form, AttachmentUploader

  mount_uploader :deposit_payment, AttachmentUploader

  mount_uploader :final_payment, AttachmentUploader

end

app/controllers/admin/umrah_customers_controller.rb
class Admin::UmrahCustomersController < ApplicationController
  before_action :set_umrah_customer, only: %i[ show edit update destroy ]
  layout 'admin'

  include CostCalculatorConcern

  # GET /umrah_customers or /umrah_customers.json
  def index
    @umrah_customers = Admin::UmrahCustomer.all
    @is_umrah_package_available = !Admin::UmrahPackage.all.blank?
  end

  # GET /umrah_customers/1 or /umrah_customers/1.json
  def show
    update_payment_status
    @umrah_package_price = calculate_customers_total_cost(@umrah_customer)
    @customer_total_paid = calculate_total_paid(@umrah_customer)
    respond_to do |format|
      format.html { render :show, locals: { umrah_customer_params: false } }
    end
  end

  # GET /umrah_customers/new
  def new
    @umrah_customer = Admin::UmrahCustomer.new
    @new_customer = @umrah_customer
  end

  # GET /umrah_customers/1/edit
  def edit
    @umrah_customer ||= Admin::UmrahCustomer.new
    @umrah_package_price = calculate_customers_total_cost(@umrah_customer)
    @customer_total_paid = calculate_total_paid(@umrah_customer)
  end

  # POST /umrah_customers or /umrah_customers.json
  def create
    @umrah_customer = Admin::UmrahCustomer.new(umrah_customer_params)
    respond_to do |format|
      if @umrah_customer.save
        format.html { redirect_to admin_umrah_customer_path(@umrah_customer.id), notice: "Umrah customer was successfully created." }
        format.json { render :show, status: :created, location: @umrah_customer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @umrah_customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /umrah_customers/1 or /umrah_customers/1.json
  def update
    @umrah_customer.update_umrah_status(params[:admin_umrah_customer][:umrah_status_attr])
    respond_to do |format|
      if @umrah_customer.update(umrah_customer_params)
        format.html { redirect_to admin_umrah_customer_path(@umrah_customer.id), notice: "Umrah customer was successfully updated." }
        format.json { render :show, status: :ok, location: @umrah_customer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @umrah_customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /umrah_customers/1 or /umrah_customers/1.json
  def destroy
    @umrah_customer.destroy

    respond_to do |format|
      format.html { redirect_to admin_umrah_customers_url, notice: "Umrah customer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def umrah_customer_params
    params
      .require(:admin_umrah_customer)
      .permit(:customer_name,
              :house_tel,
              :home_address,
              :total_participants,
              :date_registered,
              :total_paid,
              :total_cost,
              :flight_inbound_detail_id,
              :flight_outbound_detail_id,
              :quotation_form,
              :registration_form,
              :deposit_payment,
              :final_payment,
              :umrah_package_id,
              :customer_mahram,
              :mobile_tel,
              :customer_waris_name,
              :waris_address,
              :waris_tel,
              :identification_card,
              :gender,
              :citizenship,
              :is_full_payment_made,
              :umrah_status
      )
  end

  def set_umrah_customer
    @umrah_customer = Admin::UmrahCustomer.find(params[:id])
  end

  def update_payment_status
    total_paid_in_money_format = render_in_money_terms(@umrah_customer.total_paid, "")
    total_paid = total_paid_in_money_format.gsub(",", "")
    is_full_payment_made = total_paid.to_i - @umrah_customer.umrah_package.price.to_i

    if total_paid.to_i == 0
      @umrah_customer.no_payment!
    elsif is_full_payment_made == 0
      @umrah_customer.full_payment!
    elsif is_full_payment_made < 0
      @umrah_customer.partial_payment!
    else
      @umrah_customer.extra_payment!
    end

    @umrah_customer.save
  end

end

app/controllers/umrah_customers_controller.rb
class UmrahCustomersController < ApplicationController
  before_action :set_umrah_customer, only: %i[ show edit update destroy ]
  before_action :get_flight_details, only: %i[ show new edit update destroy ]
  before_action :get_customer_payment, only: %i[ edit show update destory ]
  before_action :get_umrah_package_detail, only: %i[ new edit show update destory ]

  include UmrahCustomersHelper

  # GET /umrah_customers or /umrah_customers.json
  def index
    @umrah_customers = UmrahCustomer.all
  end

  # GET /umrah_customers/1 or /umrah_customers/1.json
  def show
    @umrah_package_price =  calculate_customers_total_cost(@umrah_customer)
    respond_to do |format|
      format.html { render :show, locals: { umrah_customer_params: false } }
    end
  end

  # GET /umrah_customers/new
  def new
    @umrah_customer = UmrahCustomer.new
    @new_customer = @umrah_customer
  end

  # GET /umrah_customers/1/edit
  def edit
    @umrah_package_price = calculate_customers_total_cost(@umrah_customer)
  end

  # POST /umrah_customers or /umrah_customers.json
  def create
    @umrah_customer = UmrahCustomer.new(umrah_customer_params)

    respond_to do |format|
      if @umrah_customer.save
        format.html { redirect_to umrah_customers_path, notice: "Umrah customer was successfully created." }
        format.json { render :show, status: :created, location: @umrah_customer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @umrah_customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /umrah_customers/1 or /umrah_customers/1.json
  def update
    respond_to do |format|
      if @umrah_customer.update(umrah_customer_params)
        format.html { redirect_to umrah_customer_path, notice: "Umrah customer was successfully updated." }
        format.json { render :show, status: :ok, location: @umrah_customer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @umrah_customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /umrah_customers/1 or /umrah_customers/1.json
  def destroy
    @umrah_customer.destroy

    respond_to do |format|
      format.html { redirect_to umrah_customers_url, notice: "Umrah customer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def get_flight_details
    @flight_inbound_detail = FlightInboundDetail.all
    @flight_outbound_detail = FlightOutboundDetail.all
  end

  def get_umrah_package_detail
    @umrah_package = UmrahPackage.all
  end

  # Only allow a list of trusted parameters through.
  def umrah_customer_params
    params.require(:umrah_customer).permit(:customer_name, :house_tel, :home_address, :total_participants, :date_registered, :total_paid, :total_cost, :flight_inbound_detail_id, :flight_outbound_detail_id, :quotation_form, :registration_form, :deposit_payment, :final_payment, :umrah_package_id, :customer_mahram, :mobile_tel, :customer_waris_name, :waris_address, :waris_tel, :identification_card, :gender, :citizenship)
  end

  def get_customer_payment
    @customer_total_paid = get_total_paid
  end

end

app/helpers/admin/umrah_customers_helper.rb
module Admin
  module UmrahCustomersHelper

    def calculate_customers_total_cost(umrah_customer)
      total_package_cost = umrah_customer.umrah_package.price * umrah_customer.total_participants || 0
      ActionController::Base.helpers.number_to_currency(total_package_cost, :unit => "RM")
    end

    def get_total_paid
      @umrah_customer.total_paid.to_s
    end

    def render_status(status)
      if status.kind_of?(Array)
        status.map { |params| params.split("_").map { |status| status.capitalize
        }.join(" ")}
      else
        status.split("_").map { |status| status.capitalize
        }.join(" ")
      end
    end

  end
end

app/views/admin/umrah_customers/_form.html.erb
<div class="col-md-2">
  <%= render 'layouts/sidebar' %>
</div>
<% form_with(model: umrah_customer) do |form| %>
  <%= form.label :customer_name, "Name" %>
  <%= form.text_field :customer_name, class:"form-control customer-form-wrapper", value:@umrah_customer.customer_name %>

  <% if umrah_customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(umrah_customer.errors.count, "error") %> prohibited this umrah_customer from being saved:</h2>

      <ul>
        <% umrah_customer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/umrah_customers/edit.html.erb
<div class="row">
  <div class="col-md-8">
    <p id="notice"><%= notice %></p>
    <h1 class="admin-title">Editing Umrah Customer</h1>
    <%= link_to 'View All Customers', admin_umrah_customers_path, class: 'btn btn-primary text-white', style: "font-size:12px" %>
    <%= render partial: 'admin/umrah_customers/common/customer_form', locals: { is_display_only: false, umrah_customer: @umrah_customer } %>
  </div>
</div>

app/views/admin/umrah_customers/index.html.erb
<div class='row'>
  <div class="col-md-8">
    <p id="notice"><%= notice %></p>
    <div class="container">
      <h1 class="admin-title">Umrah Customers</h1>
      <% if @is_umrah_package_available %>
        <table class="table col-sm-12 align-self-center">
          <thead class="thead-dark text-center">
          <tr>
            <th scope="col">No</th>
            <th scope="col">Customer Name</th>
            <th scope="col">Departure Date</th>
            <th scope="col">Return Date</th>
            <th scope="col">Payment Status</th>
            <th scope="col">Umrah Status</th>
            <th scope="col"></th>
            <th scope="col"></th>
          </tr>
          </thead>
          <% @umrah_customers.each do |customer| %>
          <tbody>
          <%# @umrah_customers.each do |customer| %>
            <tr>
              <th scope="row" class="counterCell"></th>
              <td><%= customer.customer_name %></td>
              <td class="text-center"><%= customer.flight_outbound_detail.flight_departure_date_from_kl %></td>
              <td class="text-center"><%= customer.flight_inbound_detail.flight_departure_date_from_saudi %></td>
              <td class="text-center"><%= render_status(customer.is_full_payment_made) %></td>
              <td class="text-center"><%= customer.umrah_status %></td>
              <td>
                <%= link_to "View Detail", admin_umrah_customer_path(customer.id), class: "btn-sm btn-primary primary_button_text text-white", style: "font-size:12px" %>
              </td>
              <td>
                <%= link_to "Delete Customer", admin_umrah_customer_path(customer.id), { :confirm => "Are you sure you want to delete this pattern?", method: :delete, class: "btn-sm btn-danger primary_button_text text-white", style: "font-size:12px" } %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
        <br>
        <%= link_to 'New Umrah Customer', new_admin_umrah_customer_path, class: "btn btn-primary primary_button_text text-white", style: "font-size:12px" %>
      <% else %>
        <h2> Please create new Umrah Package to proceed.</h2>
        <%= link_to 'New Umrah Package', new_admin_umrah_package_path, class: "btn btn-primary primary_button_text text-white", style: "font-size:12px" %>
      <% end %>
    </div>


  </div>
</div>

app/views/admin/umrah_customers/new.html.erb
<div class="row">
  <div class="col-md-8 container">
    <p id="notice"><%= notice %></p>
    <h1 class="admin-title">New Umrah Customer</h1>
    <%= link_to 'Back', admin_umrah_customers_path, class: "nav-admin-option" %>

    <%= render partial: "admin/umrah_customers/common/customer_form", locals: { is_display_only: false } %>
  </div>
</div>

app/views/admin/umrah_customers/show.html.erb
<div class="row">
  <div class="col-md-8">
    <p id="notice"><%= notice %></p>
    <h1 class="admin-title">View Customer Details</h1>
    <%= link_to "Edit Customer Detail", edit_admin_umrah_customer_path(@umrah_customer.id), method: :get, class: 'btn btn-primary text-white', style: "font-size:12px" %>
    <%= link_to 'View All Customers', admin_umrah_customers_path, class: 'btn btn-primary text-white', style: "font-size:12px" %>
    <%= render partial: "admin/umrah_customers/common/customer_form", locals: { is_display_only: true } %>
  </div>
</div>